In [ ]:
# Import csv
# Remove Korean
# loop and scrape subs
# export csv

In [144]:
%reset -fs
import pandas as pd
from bs4 import BeautifulSoup
import requests
import time, os
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import numpy as np

In [145]:
df = pd.read_csv('music_all_90.csv')
df = df.loc[df['language'] != 'Korean']
df = df.drop(['rank', 'logo'], axis = 1)
df['start'] = np.nan
df.head()

,channel,watch_time_m,stream_time_m,peak_viewers,avg_viewers,followers,partnered,mature,language,url,t_subs,start
0,LeekBeats,107376360,122550,2985,876,25648,False,False,English,https://www.twitch.tv/LeekBeats/about,NaN,NaN
1,AmazonMusic,89461860,3660,238098,24443,382863,True,False,English,https://www.twitch.tv/AmazonMusic/about,NaN,NaN
2,Sintica,64833390,19185,9591,3379,269063,True,True,German,https://www.twitch.tv/Sintica/about,NaN,NaN
3,kubomusic,60550890,128070,1959,473,22850,False,False,English,https://www.twitch.tv/kubomusic/about,NaN,NaN
4,thegabeconcept,35970525,56100,3879,641,5703,False,False,English,https://www.twitch.tv/thegabeconcept/about,NaN,NaN

In [146]:
for i in df['channel'].head():
    print(i)

LeekBeats
AmazonMusic
Sintica
kubomusic
thegabeconcept

In [148]:
chromedriver = "/Applications/chromedriver" # initiating selenium
os.environ["webdriver.chrome.driver"] = chromedriver
driver = webdriver.Chrome(chromedriver)
web_address = 'https://twitchstats.net/streamer/'
subs = []
start = []
names = []

In [149]:
# This will break, but it will get all necessary data first
for i in df['channel']:
    driver.get(web_address + i)
    time.sleep(3 + np.random.rand())
    try:
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        # reading in the html
    except: # In case the page doesn't load properly
        names.append(i)
        subs.append('n/a')
        start.append('n/a')
        driver.close()
        driver = webdriver.Chrome(chromedriver)
    else: # Scrape name, subs, and start date
        names.append(soup.find('div', {'class': 'mst strmst'}).find('h1').text)
        subs.append(soup.find('div', {'class':'bx4'}).find('div' , {'class':'abxnm1'}).text) # reading in subs
        start.append(soup.find('div', {'class':'bx3'}).find('div' , {'class':'abxnm4'}).findNext('div').find('div', {'class':'abxnm4'}).text) # reading in start date

AttributeError: 'NoneType' object has no attribute 'find'

In [150]:
len(names)

958

In [151]:
len(subs)

958

In [152]:
df_subs = pd.DataFrame({'name':names, 'subs':subs, 'start_date':start})
df_subs.sample(40)

                         name    subs    start_date
265                Wallsterix      34  Jan 20, 2018
688            CourtneyVisser     151  Mar 21, 2020
3                   kubomusic       5  Dec 16, 2020
384                    4DJFly       -  Mar 23, 2020
710                   Jekalez     178  Sep 29, 2019
457                 995PlayFM       -  Aug 15, 2018
819  DJ_Mario_Tirolerspitzbua       -   Apr 2, 2021
236          TheTangerineClub     578   Oct 4, 2013
317                   BBRLive       -  Apr 13, 2021
51              JoPlaysViolin  2,000+   Nov 5, 2018
250         NicolePapastavrou       -   Jun 9, 2020
398                DJKharisma       -  Apr 12, 2020
437                   PSYMILL      0+  Apr 27, 2019
607           mattsuarezmusic      16  Mar 13, 2018
613           livedanslgarage       -   Feb 1, 2018
83              SkratchBastid       -  Mar 23, 2020
840             Ludgero_Rosas     119   Feb 7, 2021
119             Lost_In_House     452  Jun 24, 2014
473               DeejayRatte       -  Jan 16, 2021
295           annaluthermusic       -  Nov 28, 2020
316         NoCopyrightSounds     10+  Jul 20, 2013
359             jasonneubauer      0+  Dec 24, 2017
422                 robbflynn     65+  Mar 20, 2020
715              starlingoboe       -  Jun 23, 2020
622                  dj_maaho       -  Aug 27, 2017
52                    pealeaf     331  Jan 22, 2018
29                  astravert     617   Nov 4, 2016
166                dj_urban_o     35+  Mar 16, 2020
278                   DJOmtka       -  Aug 12, 2021
291                  faezaria     164  Jan 16, 2015
910                maria_moon       -   Sep 6, 2018
787             JamBreadMusic     180  Jun 24, 2020
440             TheDJSessions       -  Mar 31, 2016
387             DaveAudeMusic       -  Apr 22, 2020
644            moniquewinning       7   Aug 3, 2021
204               djcubalibre      0+  Apr 26, 2020
602       OfficialMikeShinoda  2,200+  Mar 17, 2020
928                 DJ_Zitros      65  Mar 17, 2020
897             mirabellejien     10+  Mar 20, 2020
182                  jfmtv_fr       -  Mar 17, 2018

In [153]:

df_subs.sample(40)

                       name    subs    start_date
550           ThisIsDayZero     35+  Aug 16, 2018
642         davidfrankdrums     580  May 30, 2019
728        Withard_Official       -  Mar 16, 2020
941            acidspacecat       -  Sep 25, 2017
518               OhhClaire     416   Jan 1, 2019
748             DavidOleart       -  Apr 22, 2020
18                 HermanLi     436  Jul 15, 2017
213            RadioHarambe       -  Dec 30, 2021
509      AmericanSongwriter       -   Aug 5, 2021
49                  SeolAhh     132  Jul 26, 2020
857          aDJcalledQUEST     116  Jan 12, 2015
592               norkstyle     65+  Mar 24, 2019
473             DeejayRatte       -  Jan 16, 2021
722         LordFinesseDITC       -  May 22, 2020
51            JoPlaysViolin  2,000+   Nov 5, 2018
825         CentralLucyPark     270   May 2, 2019
670  WastedPenguinzOfficial     262   Mar 8, 2017
851                 djedizz       -  May 13, 2020
323                   RO0PE  3,800+   Sep 7, 2018
676                  Xaeela      65   Jul 3, 2020
510            ParatronixTV  1,200+  Mar 14, 2020
206              shykuroboo     514  Aug 29, 2018
169                   upstv       1  Dec 14, 2019
879                DJLowKey       -  Mar 26, 2020
500          SuperFlu_Music     126  Mar 15, 2020
544         Animeshon_Music      0+   Dec 1, 2017
222           beatrixguitar      0+   Dec 2, 2020
581                 DJ_Yula     181  Feb 20, 2019
838               OpenMusic       -   May 7, 2020
326             boomrecords     n/a           n/a
57                  LatinUp     n/a           n/a
273                Spursito     730  Oct 15, 2015
311                 krawkmc       -  Sep 18, 2018
845               GRAFTARAT       -  Aug 19, 2019
885          VanillaKush808     n/a           n/a
899        DJDizzy_Official       -   Jan 6, 2021
665             DJ_BreckOne     200   Apr 6, 2020
869            SophieGuitar       -   Jun 1, 2021
657                 carmela     n/a           n/a
479                 blklght     224  Mar 29, 2020

'103'

channel                                      Sardoche
watch_time_m                                  5298570
stream_time_m                                    2445
peak_viewers                                     4257
avg_viewers                                      2167
followers                                     1200337
partnered                                        True
mature                                          False
language                                       French
url              https://www.twitch.tv/Sardoche/about
t_subs                                            NaN
start                                             NaN
Name: 103, dtype: object

In [156]:
df_subs = df_subs.loc[df_subs['subs'] != 'n/a'] # Getting rid of 'n/a' and '-'
df_subs = df_subs.loc[df_subs['subs'] != '-']

In [157]:
def strstrip(x):  # Formatting str -> int
    x = x.replace(",","")
    return int(x.strip("+"))

In [158]:
df_subs['subs'] = df_subs['subs'].apply(strstrip)
df_subs.head()

          name  subs    start_date
2      Sintica  9852   Sep 1, 2012
3    kubomusic     5  Dec 16, 2020
6  yejuniverse  1039  Oct 26, 2020
8      Colaway  1650  Dec 27, 2017
9   Monstercat    40  Jan 14, 2012

count      530.000000
mean       549.156604
std       1035.524186
min          0.000000
25%         65.000000
50%        182.000000
75%        472.750000
max      10000.000000
Name: t_subs, dtype: float64

In [159]:
df_subs.to_csv("music_subs_v2.csv")